### ISSUE TITLE
How To Subscribe To Delayed Market Data?

### ISSUE THREAD

**Issue by ullalaaron** [stoqey/ib#160]
Hi there!
First of all...congrats!! The library is absolutely amazing.
I'm using IBApiNext@1.2.31.

I would like to receive delayed market data from my paper account. This is what I've done:

```
export class TwsService {
  private _client = new IBApiNext({
    host: '127.0.0.1',
    port: 7497,
  });

  constructor() {
    this._client = this._client.connect();
  }

  public getMarketData(contract: Contract): Observable<MarketDataUpdate> {
    contract.exchange = 'SMART';
    this._client.setMarketDataType(MarketDataType.DELAYED);
    const obs = this._client.getMarketData(contract, '221', false, false);
    return obs;
  }
}
```

However, the error I get is:
  _error: Error: Requested market data is not subscribed. Displaying delayed market data._

What am I missing?
Thank you for your incredible work, once again

**Comment by mfrener** [comment]
Add:
_client.setMarketDataType(MarketDataType.DELAYED)

https://stoqey.github.io/ib-doc/classes/ibapinext.html#setmarketdatatype
https://interactivebrokers.github.io/tws-api/market_data_type.html

**Comment by mfrener** [comment]
this._client.setMarketDataType(MarketDataType.DELAYED); should do it (or try DELAYED_FROZEN).
Note that ticks will come in with IBApiTickType.DELAYED_ASK, IBApiTickType.DELAYED_BID, ... not  IBApiTickType.ASK,  IBApiTickType.BID, ...
Last time I checked it was still working like that (don't have an IB account anymore, so cannot try on my own)

**Comment by ullalaaron** [comment]
@mfrener Thank you for responding! From what you remember, was there anything in particular that had to be done on TWS?
I'm running out of ideas

**Comment by bouchepat** [comment]
I'm getting the same issue using the IBApi.

```
ib.reqMarketDataType(MarketDataType.DELAYED_FROZEN); // same with MarketDataType.DELAYED

ib.reqMktData(4001, {
  symbol: "AMZN",
  exchange: "SMART",
  currency: "USD",
  secType: SecType.STK,
}, '225', false, false)
```

and getting this as error:
```
Part of requested market data is not subscribed. Subscription-independent ticks are still active.AMZN NASDAQ.NMS/Auction:225 - code: 10090 - reqId: 4001
error
[
  Error: Part of requested market data is not subscribed. Subscription-independent ticks are still active.AMZN NASDAQ.NMS/Auction:225
      at Controller.emitError (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\controller.ts:207:37)
      at Decoder.decodeMsg_ERR_MSG (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\decoder.ts:699:23)
      at Decoder.processMsg (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\decoder.ts:169:21)
      at Decoder.process (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\decoder.ts:364:14)
      at Controller.processIngressQueue (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\controller.ts:100:18)
      at Socket.onMessage (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\socket.ts:303:23)
      at Socket.onData (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\socket.ts:248:16)
      at Socket.<anonymous> (E:\Repositories\ib-trader\node_modules\@stoqey\ib\src\core\io\socket.ts:145:34)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12),
  10090,
  4001
]
```
