### ISSUE TITLE
API client version missing

### ISSUE THREAD

**Issue by Digitaalne** [stoqey/ib#58]
First time trying to connect with IBKR API. I don't know if I missed some step, just I am stupid etc. Tried to google that error, but personally didn't found anything. Used just example code.

IB Gateway Build 978.2n, Feb 17, 2021 2:48:21 PM

JS:
`Uncaught TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:701)
    at Socket.send (...\node_modules\@stoqey\ib\dist\io\socket.js:166)
    at Socket.onConnect (...\node_modules\@stoqey\ib\dist\io\socket.js:315)
    at Socket.client.net_1.default.connect (...\node_modules\@stoqey\ib\dist\io\socket.js:113)
    at Object.onceWrapper (events.js:313)
    at emitNone (events.js:111)
    at Socket.emit (events.js:208)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1169)`

IB Gateway logs:
`2021-03-04 22:09:02.777 [VW] INFO  [JTS-SocketListener-48] - Error identifying stream Connection reset
2021-03-04 22:09:02.778 [VW] INFO  [JTS-SocketListener-48] - State: STOP, IsAPI: NO
2021-03-04 22:09:02.778 [VW] ERROR [JTS-SocketListener-48] - API failed to read client version
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at jextend.io.a.a(a.java:234)
	at jextend.io.a.b(a.java:208)
	at jextend.eh.d(eh.java:65)
	at jextend.bg.a(bg.java:770)
	at jextend.bg.b(bg.java:341)
	at jextend.cH.b(cH.java:349)
	at jextend.bg.p(bg.java:912)
	at jextend.ex.c(ex.java:480)
	at jextend.ex.run(ex.java:299)
	at java.lang.Thread.run(Unknown Source)
2021-03-04 22:09:02.778 [VW] WARN  [JTS-SocketListener-48] - Error
twslaunch.jutils.SLogging$Warning: API client version is missing.
	at twslaunch.jutils.at.v(at.java:263)
	at jextend.ex.run(ex.java:302)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by mfrener** [comment]
Hmm.. what node version are you using?
According to https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback Uint8Array is fine on Socket.write but according to "Invalid data, chunk must be a string or buffer" it is not.
Can you please try this let us know if fixes the problem:
./node_modules/@stoqey/ib/dist/io/socket.js - line 166 change from:
(_a = this.client) === null || _a === void 0 ? void 0 : _a.write(new Uint8Array(utf8Data));
to
(_a = this.client) === null || _a === void 0 ? void 0 : _a.write(Buffer.from(new Uint8Array(utf8Data)));

**Comment by Digitaalne** [comment]
I was using v12.16.1, upgraded to v14.16.0. Both versions gave same error.
Replaced this code like you asked and it started working well.

**Comment by mfrener** [comment]
PR is open, will be fixed in v1.1.19 (be live tomorrow or so).
https://github.com/stoqey/ib/pull/59
